### ISSUE TITLE
A way to display titles/send sounds.

### ISSUE THREAD

**Issue by roccodev** [5zig/The-5zig-API#16]
Can we get a way to display titles and send sounds?

**Comment by 5zig** [comment]
Have a look at [ModAPI#playSound](https://github.com/5zig/The-5zig-API/blob/master/src/eu/the5zig/mod/ModAPI.java#L389) and [ModAPI#createOverlay](https://github.com/5zig/The-5zig-API/blob/master/src/eu/the5zig/mod/ModAPI.java#L147).

**Comment by roccodev** [comment]
Oh so createOverlay creates also a title, and not like an "achievement"?

**Comment by 5zig** [comment]
What title do you mean?

**Comment by roccodev** [comment]
This one https://www.digminecraft.com/game_commands/images/completed_title_command_subtitle.png

**Comment by 5zig** [comment]
You can create a custom module item for that, override the render method and use the large text renderer. The problem is that the 5zig mod supports Minecraft 1.7.10, which doesn't have the title feature.
