### ISSUE TITLE
From the client how can I debug plugins

### ISSUE THREAD

**Issue by ghost** [5zig/The-5zig-API#2]
I can't even see how to check which plugins are loaded...

**Comment by 5zig** [comment]
If you really want to debug the client, you would need to add all dependencies mentioned in the json version file of the 5zig mod in .minecraft/versions, as well as the Minecraft.jar file itself and the 5zig mod installer file. Then, you create a new class with a main method in it and call net.minecraft.launchwrapper.Launch.main with the following arguments: "--assetsDir", "assets", "--userProperties", "{}", "--username", <username>, "--uuid", <uuid>, "--version", "1.8.9", "--assetIndex", "1.8", "--accessToken", <sessionId>, "--tweakClass", "eu.the5zig.mod.asm.ClassTweaker".

An alternative would be to simply add debug messages...
