### ISSUE TITLE
Can I move the player (simulate w a s d) with the plugin API?

### ISSUE THREAD

**Issue by ghost** [5zig/The-5zig-API#31]

**Comment by 5zig** [comment]
Hi, that's not possible with the plugin API and would be too much work to implement for search supported Minecraft version. You could try to search for another way to simulate wasd by Googling for "LWJGL simulate key events" or something similar. LWJGL is the OpenGL wrapper used by Minecraft and it is also used for handling keyboard and mouse events. All Minecraft versions pre 1.13 use LWJGL 2, all after 1.13 use LWJGL 3.
