### ISSUE TITLE
[question] listen to player kills/deaths

### ISSUE THREAD

**Issue by Wqrld** [5zig/The-5zig-API#4]
is there a way to get the player kills/deaths since the last login? If possible with a event being fired when you are killed/make a kill. If not, i would really like that feature

**Comment by Wqrld** [comment]
found the stats. But are events for kilsl already implemented?

**Comment by Wqrld** [comment]
And how do you get the variables out of the api? sorry, it's been a long time since i last used java.

**Comment by 5zig** [comment]
Unfortunately, there is no way of telling on the client's side how a player got killed, that's why there are no events for that in the Api. Regarding your second question, try going through the [example plugins in the repository](https://github.com/5zig/The-5zig-API/tree/master/examples).

**Comment by Wqrld** [comment]
i did that but i wasn't able to access data from the gamemode class and its not in The5zigAPI.getAPI(). So how can i access the api from the gamemode class?

**Comment by 5zig** [comment]
Either from within the [GameModeItem](https://github.com/5zig/The-5zig-API/blob/master/src/eu/the5zig/mod/modules/GameModeItem.java#L84) or the [AbstractGameListener](https://github.com/5zig/The-5zig-API/blob/master/src/eu/the5zig/mod/server/AbstractGameListener.java#L184)

**Comment by Wqrld** [comment]
thanks

**Comment by Wqrld** [comment]
sorry for me doing really dumb but can you give me a example of how to access it? It could be my setup but it seems like i can't access any of those classes

**Comment by 5zig** [comment]
You need to register them first. Just download the first example plugin from the repository and modify it by your needs.

**Comment by Wqrld** [comment]
ok ill try that

edit: wait... does this only work if the server has the game states implemented?

**Comment by 5zig** [comment]
No, the server does not need to implement anything.
