### ISSUE TITLE
possible "keyBiding" typo

### ISSUE THREAD

**Issue by ghost** [5zig/The-5zig-API#5]
https://github.com/5zig/The-5zig-API/blob/master/src/eu/the5zig/mod/ModAPI.java#L116

I think the name of the method should be `registerKeyBinding`. At the moment it has been spelt `biding` instead of `binding`.

Also, what's the category parameter's purpose? Can I put any string there?

**Comment by 5zig** [comment]
Regarding the category parameter, it is used by Minecraft for the section headers in the controls menu. Just try it out and look at the result in the GUI. :)

**Comment by ghost** [comment]
How do I update to the latest API in my own project? And does the client itself need updating at all or just the API jar?

**Comment by 5zig** [comment]
The API will be updated when the new update of the 5zig mod has been released.

**Comment by ghost** [comment]
Where's a list of all of the `Keyboard` keys possible? I tried using `Keyboard.KEY_SEMICOLON` but I think it crashed the plugin
