### ISSUE TITLE
Method for turning styled MC text into plain text?

### ISSUE THREAD

**Issue by ghost** [5zig/The-5zig-API#6]
Is there a method provided by the API that turns styled MC text into its plain text?

E.g. I'd like to be able to

```java
public void onActionBar(ActionBarEvent event) {
  message = event.getVerbatimMessage(); // returning "hey" instead of "§chey" for example
}
```

**Comment by 5zig** [comment]
Yes, just call `eu.the5zig.util.minecraft.ChatColor.stripColor(String)`. It returns the text without the `§`-color codes
