### ISSUE TITLE
How can I make module items render more frequently?

### ISSUE THREAD

**Issue by ghost** [5zig/The-5zig-API#9]

**Comment by 5zig** [comment]
What exactly do you mean?

**Comment by ghost** [comment]
Oh sorry.

Well, I set up a module item that colors different words on keypresses, but from the keypress to being rendered takes time, and it will sometimes skip a couple "frames" because i can press the key several times before it gets rendered again.

**Comment by 5zig** [comment]
That usually should not be the case. The module items get rendered every frame. Maybe try using Keyboard.isKeyDown() in your render method instead.

**Comment by ghost** [comment]
I'm currently listening to `onWorldTick` and just checking if the keybinding is pressed.

How do I use `Keyboard.isKeyDown()` instead?

**Comment by 5zig** [comment]
Call `Keyboard.isKeyDown(Keyboard.KEY_J)` in the render method of your module item to check every frame if the J key is currently pressed.
